# Cloud Build configuration file for running dag_cannon using astral uv
steps:
  - name: ghcr.io/astral-sh/uv:python3.12-alpine
    entrypoint: uv
    args: 
      - run
      - dag_cannon.py
    env:
      - COMPOSER_BUCKET_NAME=${_COMPOSER_BUCKET_NAME}

substitutions:
  _COMPOSER_BUCKET_NAME: us-central1-composer3-003baa97-bucket

options:
  machineType: e2-highcpu-32